# Generated by Django 3.1.7 on 2021-02-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Derby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('derby_type', models.CharField(max_length=100)),
                ('no_entry', models.IntegerField()),
                ('min_bet', models.FloatField()),
                ('s_date', models.DateTimeField()),
                ('e_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('owner', models.CharField(max_length=255)),
                ('entry_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('leg_band', models.CharField(max_length=255)),
                ('wing_band', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('bet', models.FloatField()),
            ],
        ),
    ]
