# Generated by Django 3.1.7 on 2021-02-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
