# Generated by Django 3.1.7 on 2021-06-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derby', '0003_entry_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='entry_id',
            field=models.IntegerField(default=5),
        ),
    ]
