# Generated by Django 3.1.7 on 2021-06-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('derby', '0004_fight_entry_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fight',
            name='entry_id',
        ),
    ]
